[profile.default]
src = "contracts"
test = "contract-test"
out = "contract-out"
cache_path = "contract-cache"
libs = ["node_modules"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/", "@gluwa/asc-contracts/=node_modules/@gluwa/asc-contracts/"]
solc_version = "0.8.30"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = true

[lint]
lint_on_build = false
