import { readFileSync, writeFileSync } from 'node:fs';
const contracts = [['itemsAbi', 'DriftItems'], ['checkoutAbi', 'DriftCheckout']];
writeFileSync('src/contract-abi.ts', '// Generated by npm run contracts.\n' + contracts.map(([name, contract]) => {
  const { abi } = JSON.parse(readFileSync(`contract-out/${contract}.sol/${contract}.json`, 'utf8'));
  return `export const ${name} = ${JSON.stringify(abi)} as const;\n`;
}).join(''));
