import { HULLS } from "./boat.ts";
import { capacity, DELIVERY_STATUS, GOOD_NAMES, itemName, type PortId, type publicWorld } from "./economy.ts";
import type { PublicChainConfig } from "./settlement.ts";

export type GuideTopic = "trade" | "commission" | "haul" | "migration" | "wallet" | "sell" | "buy";
export type GuideStep = {
  title: string; text: string; status: string; button: string;
  target: "account" | "harbor" | "workshop" | "shipyard" | "voyage" | "city" | "deck" | "chart" | "chain" | "wallet";
  port?: PortId; links?: [string, string][];
};

// Instructions read the same saved world as the workspaces; reading a page grants no progress or reward.
export function guideSteps(topic: GuideTopic, state: ReturnType<typeof publicWorld>, config: PublicChainConfig | null): GuideStep[] {
  const me = state.me, ship = state.ships[me.selectedShip], home = me.home;
  const practice = state.deliveries.find(d => d.id === "practice-timber");
  const build = state.builds?.filter(b => b.buyer === me.id).at(-1);
  const haul = state.deliveries.filter(d => d.carrier === me.id || d.reservedCarrier === me.id).at(-1);
  const bastion = state.ports.bastion, move = bastion.move;
  const order = state.settlement?.orders.filter(o => topic === "sell" ? o.seller === me.id : o.buyer === me.id).at(-1);
  const chainItem = order ? state.items[order.item] : Object.values(state.items).find(i => i.owner === me.id && i.chain);
  const itemHere = chainItem?.port ?? ship.port ?? home;
  const houseStatus = state.practice ? "You are in practice. These goods and Marks stay separate from shared play." : "Signed in as " + me.name + ". Your house and inventory are saved.";
  const walletStatus = me.wallet ? "House wallet: " + me.wallet : "Your house has no linked wallet yet.";
  const orderStatus = order ? ({draft:"Quote ready for the seller",reserved:"Fitting reserved on Creditcoin",paymentObserved:"Payment found; ownership transfer pending",verificationPending:order.sourcePaid === false ? "Unpaid return awaiting verification" : "Payment verification pending",owned:"Ownership verified; buyer owns fitting",cancelled:"Unpaid order closed; fitting returned"})[order.status] : "No Creditcoin orders for this house yet.";
  const guides: Record<GuideTopic, GuideStep[]> = {
    trade: [
      { title: "Deliver the first timber", text: "Open Market and choose Bastion. Reserve four timber from your Reedhaven warehouse for the practice order. Switch to Reedhaven and load the order cargo. Lash it to tie it down, then use Set sail to reach Bastion. Your delivery pays you and supplies the harbor office’s cargo rig.", status: state.practice ? "Practice delivery: " + (practice ? DELIVERY_STATUS[practice.status] : "unavailable") + "." : houseStatus, button: state.practice && practice?.status === "stocked" ? "Load at Reedhaven" : "Open the timber order", target: "harbor", port: practice?.status === "stocked" ? "reedhaven" : "bastion" },
      { title: "Start a merchant house", text: "Use Join harbor to create a merchant house with an invitation, or sign in to one you already own. Your house is your trading business. Choose a home city and workshop, then save the recovery code. You receive a boat and starter goods. No wallet is needed.", status: houseStatus, button: "Open House", target: "account" },
      { title: "Make something a harbor needs", text: "Open Trade chart to find orders with payment already set aside. Check the recipe in Workshop before you buy ingredients. Refineries make fuel, foundries make plates, and shipyards make fittings. Keep the ingredients in the warehouse beside your workshop.", status: (me.career?.produced ?? 0) + " goods made by your house. Home workshop: " + (me.specialty ?? "see Workshop") + ".", button: "Open Workshop", target: "workshop", port: home },
      { title: "Get paid and plan the return cargo", text: "Sell goods from your warehouse, or reserve them for a delivery order at another harbor. Load that order’s cargo and carry it to the buyer. You receive payment when the delivery completes. Before sailing home, look for another order along your route.", status: (me.career?.trades ?? 0) + " trades · " + (me.career?.hauled ?? 0) + " hauls · " + (me.career?.civic ?? 0) + " city supply orders.", button: "Open Trade chart", target: "chart" },
      { title: "Work with another house", text: "Try the Commission a boat or Arrange a delivery lesson to work with another house. Use Harbor radio in Republic to agree a price and plan the delivery. The shipwright must accept the commission. For hired deliveries, the supplier must accept the carrier’s quote.", status: Object.values(state.players).filter(p => !p.npc && p.id !== me.id).length + " other merchant houses in this world.", button: "Open harbor radio", target: "city", port: home },
    ],
    commission: [
      { title: "Choose a builder and hull", text: "Dock at a harbor with a shipyard. Open Shipyard, choose a hull and name your boat. Choose a shipwright and offer a payment in Marks. Check the materials shown beside the hull. Choose another house if you want them to build it.", status: build ? "Latest commission: " + build.name + "." : "You have not commissioned a boat yet.", button: "Open Shipyard", target: "shipyard", port: ship.port ?? home },
      { title: "Agree the work before supplying it", text: "Post the commission to set aside your payment. The shipwright must accept before construction can begin. Use Harbor radio to agree a price. Your payment stays reserved until launch. You can cancel before construction starts to return the payment and contributed materials.", status: build ? build.accepted ? "The shipwright accepted " + build.name + "." : "Waiting for the shipwright to accept." : "Choose a builder and post a commission first.", button: "Inspect the commission", target: "shipyard", port: build?.port ?? ship.port ?? home },
      { title: "Deliver the materials to that harbor", text: "Buy timber, plates and fuel, or post delivery orders with payment set aside. Move the materials to the harbor where the boat will be built. Each contributor must dock there and supply materials from their own warehouse.", status: build ? "Timber: " + (build.stock.timber ?? 0) + "/" + HULLS[build.hull].timber + ". Plates: " + (build.stock.plates ?? 0) + "/" + HULLS[build.hull].plates + ". Fuel: " + (build.stock.fuel ?? 0) + "/2." : "Choose a hull to see the materials it needs.", button: "Arrange deliveries", target: "harbor", port: build?.port ?? ship.port ?? home },
      { title: "Launch your boat", text: "Construction starts when the shipwright has accepted and all materials have arrived. It takes one minute. At launch, the shipwright receives the payment, less any agreed advance repayment. Your boat appears in Your fleet. Select its name to use it.", status: build?.launched ? build.name + " has launched." : build?.readyAt ? "Construction is underway." : "Construction is waiting for acceptance or materials.", button: "Check construction", target: "shipyard", port: build?.port ?? ship.port ?? home },
    ],
    haul: [
      { title: "Find a supplier who needs a carrier", text: "Open Market’s Carrier directory, set your starting fee and turn on Available for hauling. Look for a delivery marked Ready to load. Its supplier has already reserved the goods. If none are ready, use Harbor radio to offer your help.", status: me.available ? "Your house is available for hauling." : "You are not listed as available for deliveries.", button: "Find cargo and carriers", target: "harbor", port: ship.port ?? home },
      { title: "Quote a fee and wait to be hired", text: "Enter a hauling fee on another supplier’s order and choose Quote delivery fee. The supplier chooses Hire carrier to accept. Check the destination, deadline and cargo before quoting. Your fee comes from the order’s total payment. The supplier receives the rest after any city fee.", status: haul ? "Your latest job: " + haul.quantity + " " + GOOD_NAMES[haul.good] + " · hauling fee " + haul.fee + " Marks · " + DELIVERY_STATUS[haul.status] + "." : "No order is reserved for you yet.", button: "Review haul offers", target: "harbor", port: haul?.from ?? ship.port ?? home },
      { title: "Load the order cargo", text: "Dock at the harbor where the goods are waiting. Choose Load order cargo on the job assigned to you. This cargo belongs to the delivery order, so you cannot sell it separately. Check both deck space and weight limits. A cargo rig or larger hull gives you more room.", status: haul ? "Origin: " + (haul.from ? state.ports[haul.from].name : "not stocked") + ". Order is " + DELIVERY_STATUS[haul.status] + ". Selected boat: " + capacity(state, ship) + " deck spaces." : "Get hired for an order before you sail to collect it.", button: "Open the loading harbor", target: "harbor", port: haul?.from ?? ship.port ?? home },
      { title: "Compare passages and protect the cargo", text: "Open More, then Aboard, and choose Lash cargo to tie it down. Use Set sail to compare the travel time, fuel, docking fee and hull wear. Repair the boat if needed. Choose a route that reaches the buyer before the deadline.", status: ship.voyage ? "Underway to " + state.ports[ship.voyage.port].name + "." : "Boat is " + (ship.port ? "docked at " + state.ports[ship.port].name : "at sea") + ".", button: "Plan the delivery passage", target: "voyage", port: haul?.to ?? "bastion" },
      { title: "Confirm delivery and your payment", text: "Arrival delivers the cargo and pays the supplier and carrier. Check the order and Recent notices. If the buyer’s warehouse is full, the cargo stays aboard until they make room. Look for a return delivery in Market. The buyer or supplier can cancel before departure; a sailing order cannot be cancelled.", status: haul?.status === "delivered" ? "Your latest haul was delivered for a " + haul.fee + "-Mark carrier payment." : "Your latest delivery is not complete yet.", button: "Inspect destination work", target: "harbor", port: haul?.to ?? "bastion" },
    ],
    migration: [
      { title: "Coordinate with Bastion’s residents", text: "Only Bastion moves in this region. Open Republic at Bastion to discuss its next anchorage on Harbor radio. Resident houses elect a steward, who schedules the move. If your house belongs to another city, ask a Bastion resident to coordinate.", status: bastion.steward ? "Steward: " + (state.players[bastion.steward]?.name ?? "recorded house") + "." : "Bastion has no steward yet.", button: "Visit Bastion’s council", target: "city", port: "bastion" },
      { title: "Bring fuel and compare trading grounds", text: "Bastion needs 15 fuel in its city stores before it can move. Bring fuel to your Bastion warehouse and contribute it in Republic. Compare the east and west routes before choosing. Contributions come from the warehouse, not your boat’s fuel tank.", status: "Bastion has " + (bastion.treasury.fuel ?? 0) + " fuel in city stores. Your local warehouse has " + (me.warehouse.bastion.fuel ?? 0) + ".", button: "Compare and contribute", target: "city", port: "bastion" },
      { title: "Prepare during the departure notice", text: "The steward schedules the move once the fuel is available. You get at least five minutes’ notice before a two-minute journey. Review your deliveries and check whether your boat is docked at Bastion. Gathering pauses during the move. Workshop jobs already in progress still finish.", status: move ? Date.now() < move.departAt ? "Departure announced. Check the countdown in Republic." : "Bastion is travelling to its next anchorage." : "No move is scheduled.", button: "Check the migration plan", target: "city", port: "bastion" },
      { title: "Replan after the city anchors", text: "Open Trade chart after Bastion anchors and compare the new routes. Its timber gardens move with the city. Existing delivery orders keep their agreed berth and protected deadlines. Check each order’s destination. Agree new hauling fees for future orders.", status: "Bastion berth " + bastion.berth + (move ? " · migration underway or announced." : " · anchored.") , button: "Compare the new routes", target: "chart" },
    ],
    wallet: [
      { title: "Start with a saved merchant house", text: "Create or sign in to a merchant house and save its recovery code. Creditcoin records ownership of fittings published from shared play. Practice goods stay separate. Sailing, crafting and trade in Marks do not need a wallet.", status: houseStatus, button: "Open House", target: "account" },
      { title: "Choose and link your wallet", text: "Choose Connect wallet and select a browser wallet, or use WalletConnect to pair a phone. Connecting only shares your address. In wallet details, choose Link to this house and sign the message after checking the house and account. This does not spend funds. Disconnecting leaves the house link in place.", status: walletStatus, button: "Open wallet details", target: "wallet" },
      { title: "Get the two test currencies", text: "The buyer pays the fitting price and transaction fee with Sepolia test ETH. The seller needs test CTC for the Creditcoin reservation fee. The game service submits publication and installation changes. Use the faucet links below, then choose Check test balances in wallet details. Marks are separate game currency.", status: config?.mode === "local" ? "This harbor uses local test networks. Public testnet funds cannot be used here." : "Payment: Ethereum Sepolia, chain 11155111. Items: Creditcoin Testnet, chain 102031.", button: "Open wallet details", target: "wallet", links: [["Sepolia faucet list", "https://ethereum.org/developers/docs/networks/#sepolia"], ["Creditcoin test-token instructions", "https://docs.creditcoin.org/wallets/using-testnet-faucet"]] },
      { title: "Choose the seller or buyer lesson", text: "Open the Creditcoin fitting market in Shipyard. The seller records a crafted fitting, quotes a price to a linked house and reserves it. The buyer pays on Sepolia after the reservation is confirmed. Creditcoin verifies the payment before transferring ownership. Follow the seller or buyer lesson for each step.", status: !config ? "Creditcoin trades are not enabled in this harbor." : config.readOnly ? "Creditcoin trades are paused. You can link a wallet and check ownership." : "Creditcoin is connected. Check the market’s availability before trading.", button: "Open Creditcoin market", target: "chain", port: ship.port ?? home },
    ],
    sell: [
      { title: "Craft a fitting", text: "A cargo rig needs 4 timber, 3 plates and 1 repair kit at a shipyard. Craft it and leave it uninstalled. Both the maker and seller need linked wallets before the fitting can be recorded on Creditcoin. Engines and livery kits can also be sold this way.", status: walletStatus, button: "Open my workshop", target: "workshop", port: home },
      { title: "Record the fitting on Creditcoin", text: "Dock your own boat at the fitting’s harbor. Under Your fittings in Shipyard, choose Record on Creditcoin. The game checks the crafting record and submits the transaction. Wait for confirmed ownership before you offer the fitting for sale.", status: chainItem ? "Fitting: " + itemName(chainItem) + " · " + (chainItem.chain?.task ? "waiting for a Creditcoin update" : chainItem.chain?.status === "minting" ? "waiting to be recorded on Creditcoin" : chainItem.chain ? "recorded on Creditcoin" : "not recorded on Creditcoin") + "." : "No fitting is recorded on Creditcoin for your house yet.", button: "Open Your fittings", target: "shipyard", port: itemHere },
      { title: "Quote to a specific buyer", text: "Open the Creditcoin fitting market. Choose an uninstalled fitting, a buyer with a linked wallet, a price and a payment window. Choose Create quote. Under Order details, check the fitting, buyer, seller, price, deadline and both contract addresses.", status: orderStatus, button: "Review a quote", target: "chain", port: itemHere },
      { title: "Sign and reserve on Creditcoin", text: "Choose Sign quote and reserve fitting. Review the quote signature and Creditcoin reservation transaction in your wallet. The buyer can pay once the reservation is confirmed. Ask them to review the order from their own house. Payment must go through the game’s checkout.", status: orderStatus, button: "Inspect reservation", target: "chain", port: itemHere },
      { title: "Wait for the ownership transfer", text: "After Sepolia confirms the payment, the game submits its proof to Creditcoin for verification. The fitting stays reserved until this finishes, even after the payment deadline. For an unpaid order, choose Close unpaid order on Sepolia after the deadline. Verified closure returns the fitting. Check the receipts before retrying.", status: orderStatus, button: "Check the order", target: "chain", port: itemHere },
    ],
    buy: [
      { title: "Agree a price with the seller", text: "Link your wallet and agree a fitting and price with another house. Ask the seller to quote to your house. In the Creditcoin fitting market, check the fitting and recipient addresses. Payment becomes available only after the seller reserves the fitting.", status: walletStatus + " " + orderStatus, button: "Open Creditcoin orders", target: "chain", port: itemHere },
      { title: "Review and pay on Sepolia", text: "Wait for Fitting reserved on Creditcoin, then choose Review payment in wallet. Check the network, recipient contract, price and transaction fee before approving. The game checks that the reservation is confirmed and your wallet matches the buyer. Rejecting the prompt sends no payment. Check a pending transaction before retrying.", status: orderStatus, button: "Review the payment order", target: "chain", port: itemHere },
      { title: "Wait for confirmed ownership", text: "A recorded payment is not yet a completed transfer. You can keep playing while Creditcoin verifies it. Choose Check status to refresh. Wait for Ownership verified; buyer owns fitting. The payment deadline does not refund a paid order or return its fitting to the seller.", status: orderStatus, button: "Check verification", target: "chain", port: itemHere },
      { title: "Dock and install the fitting", text: "After ownership is verified, dock your own boat at the fitting’s harbor. Open Your fittings in Shipyard. Remove the fitting in that slot if needed. Choose Install on Creditcoin and wait for confirmation. Applying a livery kit uses it up. Cargo rigs and engines can be removed later.", status: chainItem?.owner === me.id ? chainItem.installed ? "The fitting is installed on " + (state.ships[chainItem.installed]?.name ?? "your boat") + "." : "Your fitting is at " + state.ports[itemHere].name + "." : "Your house does not yet own a purchased fitting.", button: "Open Your fittings", target: "shipyard", port: itemHere },
      { title: "Carry more cargo", text: "A cargo rig adds four deck spaces and reduces sailing speed by 10%. A basic cutter goes from 12 spaces to 16. Try a 14-unit delivery to use the extra room. Check the weight limit too, lash the cargo and complete the trip. Unload excess cargo before removing the rig.", status: "Selected boat: " + capacity(state, ship) + " deck spaces" + (ship.modules.cargoModule ? " · cargo rig fitted." : " · no cargo rig fitted."), button: "Find a useful delivery", target: "chart" },
    ],
  };
  return guides[topic];
}
